# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('helics-example', ['helics', 'core', 'point-to-point', 'csma', 'internet', 'applications'])
    obj.source = 'helics-example.cc'

