/*
 * Copyright (c) 2023 Universita' degli Studi di Napoli Federico II
 *
 * SPDX-License-Identifier: GPL-2.0-only
 *
 * Author: Stefano Avallone <stavallo@unina.it>
 */

#ifndef WIFI_EMLSR_P2P_TEST_H
#define WIFI_EMLSR_P2P_TEST_H

#include "wifi-emlsr-test-base.h"

#include <list>

/**
 * @ingroup wifi-test
 * @ingroup tests
 *
 * @brief Base class to setup an adhoc peer that exchanges data with an EMLSR client.
 *
 */
class EmlsrP2pOperationsTestBase : public EmlsrOperationsTestBase
{
  public:
    /**
     * Constructor
     *
     * @param name The name of the new TestCase created
     */
    EmlsrP2pOperationsTestBase(const std::string& name);
    ~EmlsrP2pOperationsTestBase() override = default;

  protected:
    void DoSetup() override;
    void DoRun() override;
    void Transmit(Ptr<WifiMac> mac,
                  uint8_t phyId,
                  WifiConstPsduMap psduMap,
                  WifiTxVector txVector,
                  double txPowerW) override;

    /**
     * @param fromEmlsrToAdhoc true if traffic is generated by EMLSR client, false if traffic is
     *                         generated by the adhoc peer
     * @param count the number of packets to generate
     * @param pktSize the size of the packets to generate
     * @return an application generating the given number packets of the given size from/to the
     *         EMLSR client to/from the adhoc peer
     */
    Ptr<PacketSocketClient> GetP2pApplication(bool fromEmlsrToAdhoc,
                                              std::size_t count,
                                              std::size_t pktSize) const;

    /// Actions and checks to perform upon the transmission of each frame
    struct Events
    {
        /**
         * Constructor.
         *
         * @param type the frame MAC header type
         * @param f function to perform actions and checks
         */
        Events(WifiMacType type,
               std::function<void(Ptr<const WifiPsdu>, const WifiTxVector&, uint8_t)>&& f = {})
            : hdrType(type),
              func(f)
        {
        }

        WifiMacType hdrType; ///< MAC header type of frame being transmitted
        std::function<void(Ptr<const WifiPsdu>, const WifiTxVector&, uint8_t)>
            func; ///< function to perform actions and checks
    };

    Ptr<AdhocWifiMac> m_adhocMac;     //!< the MAC of the adhoc peer
    const uint8_t m_infraLinkId{1};   //!< ID of the link used for infra data exchange
    const uint8_t m_p2pLinkId{2};     //!< ID of the link used for P2P data exchange
    bool m_emlsrAwareAdhocPeer{true}; //!< whether the adhoc peer is EMLSR aware
    std::list<Events> m_events;       //!< list of events for a test run
    std::size_t m_processedEvents{0}; //!< number of processed events
    bool m_setupDone{false}; //!< whether the setup (including BA agreements) has been completed

  private:
    /**
     * Activate beacon generation on adhoc peer, so that EMLSR client and adhoc peer know each
     * other, then establish block ack agreements between EMLSR client and adhoc peer and finally
     * call DoStartTraffic.
     */
    void StartTraffic() override;

    /// actually start generation of traffic
    virtual void DoStartTraffic() = 0;

    PacketSocketAddress
        m_emlsrToAdhocSockAddr; //!< packet socket address for EMLSR client to adhoc peer traffic
    PacketSocketAddress
        m_adhocToEmlsrSockAddr; //!< packet socket address for adhoc peer to EMLSR client traffic
};

/**
 * @ingroup wifi-test
 * @ingroup tests
 *
 * @brief Test data exchange between an EMLSR client and an adhoc peer.
 *
 * An EMLSR client setups 3 links with an AP MLD and EMLSR mode is enabled on all three links.
 * A TID-to-Link Mapping is configured so that only one link (differing from the preferred link)
 * is used for data exchange between the EMLSR client and the AP MLD. Another link (differing from
 * the preferred link) is used for data exchange between the EMLSR client and a single-link adhoc
 * peer. The EMLSR client carries out both a DL TXOP and an UL TXOP with both the AP MLD and the
 * adhoc peer (at different times). In every TXOP, the CTS frame is corrupted once. It is verified
 * that data exchanges take place on the expected link and all the expected frames are exchanged
 * during the TXOPs. All combinations of values for the SwitchAuxPhy and PutAuxPhyToSleep attributes
 * are tested. It is also verified that the UpdateCwAfterFailedIcf attribute of
 * AdvancedApEmlsrManager and the EmlsrUpdateCwAfterFailedIcf attribute of AdhocWifiMac work as
 * expected.
 */
class EmlsrAdhocPeerTest : public EmlsrP2pOperationsTestBase
{
  public:
    /**
     * Constructor.
     *
     * @param switchAuxPhy whether aux PHYs switch link
     * @param auxPhySleepAndUpdateCw whether aux PHYs are put to sleep during DL/UL TXOPs and
     *                               whether CW is updated after ICF failure
     */
    EmlsrAdhocPeerTest(bool switchAuxPhy, bool auxPhySleepAndUpdateCw);

  protected:
    void DoSetup() override;

    /**
     * Simulate a DL TXOP and an UL TXOP between the EMLSR client and either the AP MLD or the
     * adhoc peer.
     *
     * @param mac the MAC of the device exchanging data with the EMLSR client
     */
    void RunOne(Ptr<WifiMac> mac);

  private:
    void DoStartTraffic() override;

    bool m_switchAuxPhy;                   //!< whether aux PHYs switch link
    bool m_updateCwAfterIcfFailure;        //!< whether to update adhoc peer's CW after ICF failure
    Ptr<ListErrorModel> m_staErrorModel;   ///< error rate model to install on EMLSR client
    Ptr<ListErrorModel> m_otherErrorModel; ///< error rate model to install on AP MLD or adhoc peer
};

/**
 * @ingroup wifi-test
 * @ingroup tests
 *
 * @brief Test data exchange between an EMLSR client and an EMLSR-unaware adhoc peer.
 *
 * An EMLSR client setups 3 links with an AP MLD and EMLSR mode is enabled on all three links.
 * A TID-to-Link Mapping is configured so that the preferred link is only used for data exchange
 * between the EMLSR client and a single-link EMLSR-unaware adhoc peer. The aux PHYs of the EMLSR
 * client do not switch link, so that the main PHY always returns to the preferred link. This test
 * verifies that the EMLSR client is able to successfully receive the following frames, when sent
 * on the preferred link:
 * - single MPDU carrying QoS data frame
 * - A-MPDU
 * - RTS
 * - BlockAckReq
 */
class EmlsrUnawareAdhocPeerTest : public EmlsrP2pOperationsTestBase
{
  public:
    EmlsrUnawareAdhocPeerTest();

  protected:
    void DoSetup() override;

    /// Generate packets that the adhoc peer sends to the EMLSR client and check correctness of
    /// the operations.
    void RunOne();

  private:
    void DoStartTraffic() override;

    const std::size_t m_payloadSize{750}; //!< size of payload in bytes
    Ptr<ListErrorModel> m_staErrorModel;  ///< error rate model to install on the EMLSR client
};

/**
 * @ingroup wifi-test
 * @ingroup tests
 *
 * @brief wifi EMLSR suite to test operations with adhoc P2P client
 */
class WifiEmlsrP2pTestSuite : public TestSuite
{
  public:
    WifiEmlsrP2pTestSuite();
};

#endif /* WIFI_EMLSR_P2P_TEST_H */
