#ifndef UNITS_FREQUENCY_ATTRIBS_H
#define UNITS_FREQUENCY_ATTRIBS_H

#include "units-frequency.h"

#include "ns3/attribute-helper.h"
#include "ns3/attribute.h"
#include "ns3/double.h"

namespace ns3
{

/// @cond To suppress doxygen checker
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(Hz_t, Hz);
ATTRIBUTE_ACCESSOR_DEFINE(Hz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(Hz_t, Hz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(kHz_t, kHz);
ATTRIBUTE_ACCESSOR_DEFINE(kHz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(kHz_t, kHz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(MHz_t, MHz);
ATTRIBUTE_ACCESSOR_DEFINE(MHz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(MHz_t, MHz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(GHz_t, GHz);
ATTRIBUTE_ACCESSOR_DEFINE(GHz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(GHz_t, GHz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(THz_t, THz);
ATTRIBUTE_ACCESSOR_DEFINE(THz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(THz_t, THz, Double);
/// @endcond

} // namespace ns3

#endif // UNITS_FREQUENCY_ATTRIBS_H
