#include "units-frequency-attributes.h"

using namespace ns3;

// clang-format off
namespace ns3
{
/// @cond Doxygen warning against macro internal
ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(Hz_t, Hz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(Hz_t, Hz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(kHz_t, kHz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(kHz_t, kHz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(MHz_t, MHz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(MHz_t, MHz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(GHz_t, GHz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(GHz_t, GHz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(THz_t, THz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(THz_t, THz);
/// @endcond

} // namespace ns3
