## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('nix-vector-routing', ['internet'])
    module.includes = '.'
    module.source = [
        'model/nix-vector-routing.cc',
        'helper/nix-vector-helper.cc',
        ]

    nix_vector_test = bld.create_ns3_module_test_library('nix-vector-routing')
    nix_vector_test.source = [
        'test/nix-test.cc',
    ]

    headers = bld(features='ns3header')
    headers.module = 'nix-vector-routing'
    headers.source = [
        'model/nix-vector-routing.h',
        'helper/nix-vector-helper.h',
        ]
    headers.deprecated = [
        'model/ipv4-nix-vector-routing.h',
        'helper/ipv4-nix-vector-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
