## -*-Mode : python; py-indent-offset : 4; indent-tabs-mode : nil; coding : utf-8; -*-

import wutils

# Required NetAnim version
NETANIM_RELEASE_NAME = "netanim-3.108"

def build (bld) :
    module = bld.create_ns3_module ('netanim', ['internet', 'mobility', 'wimax', 'wifi', 'csma', 'lte', 'uan', 'lr-wpan', 'energy', 'wave'])
    module.includes = '.'
    module.source = [ 'model/animation-interface.cc', ]
    netanim_test = bld.create_ns3_module_test_library('netanim')
    netanim_test.source = ['test/netanim-test.cc', ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        netanim_test.source.extend([
        #   'test/netanim-examples-test-suite.cc',
            ])
    
    headers = bld(features='ns3header')
    headers.module = 'netanim'
    headers.source = ['model/animation-interface.h', ]
    if (bld.env['ENABLE_EXAMPLES']) :
       bld.recurse('examples')
    bld.ns3_python_bindings()
