#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-2.0-only

import argparse

import matplotlib

matplotlib.use("Agg")

import matplotlib.animation as animation
import matplotlib.patches as patches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D

TRACE_FILE = "3gpp-channel-consistency-output.txt"
BUILDINGS_FILE = "3gpp-channel-consistency-buildings.txt"

TIME_COL = "Time[s]"
TX_X_COL = "TxPosX[m]"
TX_Y_COL = "TxPosY[m]"
RX_X_COL = "RxPosX[m]"
RX_Y_COL = "RxPosY[m]"
STATE_COL = "ChannelState"
SNR_COL = "SNR[dB]"

CLUSTER_POWER_COLS = [
    "1st_C_Power[dB]",
    "2nd_C_Power[dB]",
    "3rd_C_Power[dB]",
]
COMPONENT_POWER_COLS = [
    "C1ComponentPower[dB]",
    "C2ComponentPower[dB]",
    "C3ComponentPower[dB]",
]
DELAY_COLS = ["1st_C_Delay[s]", "2nd_C_Delay[s]", "3rd_C_Delay[s]"]
AOA_COLS = ["1st_C_Aoa[Degree]", "2nd_C_Aoa[Degree]", "3rd_C_Aoa[Degree]"]
ZOA_COLS = ["1st_C_Zoa[Degree]", "2nd_C_Zoa[Degree]", "3rd_C_Zoa[Degree]"]

COMPONENT_LABELS = ["C1", "C2", "C3"]
COMPONENT_STYLES = ["-", "--", ":"]
COMPONENT_COLORS = ["tab:blue", "tab:orange", "tab:green"]

SNR_Y_LIMITS = (-50, 50)
SNR_DIFF_Y_LIMITS = (-35, 25)
ZOOM_WINDOW_S = 0.05


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Plot traces generated by three-gpp-channel-consistency-example."
    )
    parser.add_argument(
        "--animations",
        action="store_true",
        help="Also generate the map/SNR and channel-component-power animations.",
    )
    return parser.parse_args()


def angular_difference_deg(series):
    """Return per-sample angular changes without wraparound discontinuities."""
    values = series.to_numpy()
    unwrapped = np.unwrap(np.radians(values))
    differences = np.diff(unwrapped, prepend=unwrapped[0])
    return pd.Series(np.degrees(differences), index=series.index)


def padded_limits(series_list, padding=0.1, minimum_span=1.0):
    """Return common plot limits for one or more numeric series."""
    values = np.concatenate([np.asarray(series) for series in series_list])
    value_min = float(np.nanmin(values))
    value_max = float(np.nanmax(values))
    span = max(value_max - value_min, minimum_span)
    margin = padding * span
    return value_min - margin, value_max + margin


def symmetric_limits(series_list, padding=0.2, minimum=1.0):
    """Return symmetric limits around zero for one or more numeric series."""
    values = np.concatenate([np.asarray(series) for series in series_list])
    maximum = max(float(np.nanmax(np.abs(values))), minimum)
    return -(1.0 + padding) * maximum, (1.0 + padding) * maximum


def get_transition_times(time, state):
    """Return NLOS-to-LOS and LOS-to-NLOS transition times."""
    previous_state = state.shift(1, fill_value=state.iloc[0])
    nlos_to_los = []
    los_to_nlos = []

    for timestamp, previous, current in zip(time, previous_state, state):
        if previous == current:
            continue
        if previous.startswith("NLOS") and current == "LOS":
            nlos_to_los.append(timestamp)
        elif previous == "LOS" and current.startswith("NLOS"):
            los_to_nlos.append(timestamp)

    return nlos_to_los, los_to_nlos


def add_state_vlines(axis, nlos_to_los, los_to_nlos):
    """Draw channel-state transitions on an axis."""
    for timestamp in nlos_to_los:
        axis.axvline(timestamp, color="green", linestyle="-", linewidth=0.9, alpha=0.6)
    for timestamp in los_to_nlos:
        axis.axvline(timestamp, color="red", linestyle="--", linewidth=0.9, alpha=0.6)


def add_state_legend(axis, nlos_to_los, los_to_nlos, location="best"):
    """Add a legend for channel-state transitions that occur in the trace."""
    handles = []
    if nlos_to_los:
        handles.append(Line2D([0], [0], color="green", linestyle="-", label="NLOS to LOS"))
    if los_to_nlos:
        handles.append(Line2D([0], [0], color="red", linestyle="--", label="LOS to NLOS"))
    if handles:
        axis.legend(handles=handles, loc=location)


def scenario_limits(buildings, tx_x, tx_y, rx_x, rx_y):
    """Return bounds containing the buildings and complete node trajectories."""
    x_values = np.concatenate(
        [buildings[0].to_numpy(), buildings[2].to_numpy(), tx_x.to_numpy(), rx_x.to_numpy()]
    )
    y_values = np.concatenate(
        [buildings[1].to_numpy(), buildings[3].to_numpy(), tx_y.to_numpy(), rx_y.to_numpy()]
    )
    x_min, x_max = float(x_values.min()), float(x_values.max())
    y_min, y_max = float(y_values.min()), float(y_values.max())
    margin = max(0.05 * max(x_max - x_min, y_max - y_min), 5.0)
    return (x_min - margin, x_max + margin), (y_min - margin, y_max + margin)


def add_buildings(axis, buildings):
    """Draw all scenario buildings on an axis."""
    for _, building in buildings.iterrows():
        x_min, y_min, x_max, y_max = building
        rectangle = patches.Rectangle(
            (x_min, y_min),
            x_max - x_min,
            y_max - y_min,
            facecolor="gray",
            edgecolor="black",
            alpha=0.5,
            linewidth=0.8,
        )
        axis.add_patch(rectangle)


def coordinate_label(name, x, y):
    return f"{name} ({x:.2f}, {y:.2f}) m"


def plot_scenario(output_filename, buildings, tx_x, tx_y, rx_x, rx_y, x_limits, y_limits):
    """Generate a static figure of the buildings and RX trajectory."""
    figure, axis = plt.subplots(figsize=(8, 8))
    add_buildings(axis, buildings)

    axis.plot(
        rx_x,
        rx_y,
        color="tab:orange",
        linewidth=2.0,
        label="RX trajectory",
        zorder=3,
    )
    axis.scatter(
        tx_x.iloc[0],
        tx_y.iloc[0],
        marker="^",
        color="blue",
        s=110,
        label=coordinate_label("TX", tx_x.iloc[0], tx_y.iloc[0]),
        zorder=4,
    )
    axis.scatter(
        rx_x.iloc[0],
        rx_y.iloc[0],
        marker="o",
        color="green",
        s=80,
        label=coordinate_label("RX start", rx_x.iloc[0], rx_y.iloc[0]),
        zorder=4,
    )
    axis.scatter(
        rx_x.iloc[-1],
        rx_y.iloc[-1],
        marker="x",
        color="red",
        s=110,
        linewidth=2.5,
        label=coordinate_label("RX end", rx_x.iloc[-1], rx_y.iloc[-1]),
        zorder=4,
    )

    axis.set_xlabel("X [m]", fontsize=18)
    axis.set_ylabel("Y [m]", fontsize=18)
    axis.set_title("Simulation scenario", fontsize=20)
    axis.set_aspect("equal")
    axis.set_xlim(*x_limits)
    axis.set_ylim(*y_limits)
    axis.grid(True, linewidth=0.4, alpha=0.5)
    axis.legend(loc="best", fontsize=18)
    axis.tick_params(axis="both", labelsize=18)
    figure.tight_layout()
    figure.savefig(output_filename, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_snr(output_filename, time, snr, snr_diff, nlos_to_los, los_to_nlos):
    """Generate the static SNR and SNR-change figure."""
    figure, axes = plt.subplots(2, 1, figsize=(10, 6), sharex=True)

    axes[0].plot(time, snr, "k-", linewidth=1.2)
    axes[0].set_ylabel("SNR [dB]")
    axes[0].set_ylim(*SNR_Y_LIMITS)
    axes[0].grid(True)
    add_state_vlines(axes[0], nlos_to_los, los_to_nlos)
    add_state_legend(axes[0], nlos_to_los, los_to_nlos)

    axes[1].plot(time, snr_diff, "k-", linewidth=1.2)
    axes[1].set_ylabel(r"$\Delta$ SNR [dB]")
    axes[1].set_xlabel("Time [s]")
    axes[1].set_ylim(*SNR_DIFF_Y_LIMITS)
    axes[1].grid(True)
    add_state_vlines(axes[1], nlos_to_los, los_to_nlos)

    axes[0].set_xlim(time.min(), time.max())
    figure.tight_layout()
    figure.savefig(output_filename, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_components(axis, time, components, nlos_to_los, los_to_nlos):
    """Plot C1-C3 on one axis."""
    for index, (label, style, color, component) in enumerate(
        zip(COMPONENT_LABELS, COMPONENT_STYLES, COMPONENT_COLORS, components)
    ):
        axis.plot(
            time,
            component,
            linestyle=style,
            color=color,
            linewidth=1.3,
            label=label,
            zorder=len(COMPONENT_LABELS) - index,
        )
    add_state_vlines(axis, nlos_to_los, los_to_nlos)
    axis.set_xlim(time.min(), time.max())
    axis.grid(True)
    axis.legend(loc="best")


def plot_cluster_overview(
    output_filename,
    time,
    component_powers,
    delays_us,
    component_power_differences,
    delay_differences_us,
    nlos_to_los,
    los_to_nlos,
):
    """Generate an overview of channel component powers and delays for C1-C3."""
    figure, axes = plt.subplots(2, 2, figsize=(14, 8), sharex=True)
    plots = [
        (axes[0, 0], component_powers, "Channel component power [dB]"),
        (axes[0, 1], delays_us, r"Cluster delay [$\mu$s]"),
        (axes[1, 0], component_power_differences, "Changes in channel component power [dB]"),
        (axes[1, 1], delay_differences_us, r"$\Delta$ delay [$\mu$s]"),
    ]

    for axis, components, ylabel in plots:
        plot_components(axis, time, components, nlos_to_los, los_to_nlos)
        axis.set_ylabel(ylabel)
        axis.set_xlabel("Time [s]")

    axes[0, 0].set_ylim(*padded_limits(component_powers, minimum_span=1.0))
    axes[0, 1].set_ylim(*padded_limits(delays_us, minimum_span=0.1))
    axes[1, 0].set_ylim(*symmetric_limits(component_power_differences, minimum=0.1))
    axes[1, 1].set_ylim(*symmetric_limits(delay_differences_us, minimum=0.01))

    figure.tight_layout()
    figure.savefig(output_filename, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_third_cluster_metrics(
    output_filename,
    time,
    cluster_powers,
    delays_us,
    aoas,
    cluster_power_differences,
    delay_differences_us,
    aoa_differences,
    nlos_to_los,
    los_to_nlos,
):
    """Plot the third-cluster power, delay, AoA, and their per-sample changes."""
    figure, axes = plt.subplots(2, 3, figsize=(16, 6), sharex="col")

    third_power = cluster_powers[2]
    third_delay = delays_us[2]
    third_aoa = aoas[2]

    third_power_difference = cluster_power_differences[2]
    third_delay_difference = delay_differences_us[2]
    third_aoa_difference = aoa_differences[2]

    axes[0, 0].plot(time, third_power, "k-", linewidth=1.2)
    axes[0, 0].set_ylabel("Power [dB]")
    axes[0, 0].grid(True)
    add_state_vlines(axes[0, 0], nlos_to_los, los_to_nlos)
    add_state_legend(axes[0, 0], nlos_to_los, los_to_nlos, location="lower right")

    axes[0, 1].plot(time, third_delay, "k-", linewidth=1.2)
    axes[0, 1].set_ylabel(r"Delay [$\mu$s]")
    axes[0, 1].grid(True)
    add_state_vlines(axes[0, 1], nlos_to_los, los_to_nlos)

    axes[0, 2].plot(time, third_aoa, "k-", linewidth=1.2)
    axes[0, 2].set_ylabel("AoA [deg]")
    axes[0, 2].grid(True)
    add_state_vlines(axes[0, 2], nlos_to_los, los_to_nlos)

    axes[1, 0].plot(time, third_power_difference, "k-", linewidth=1.2)
    axes[1, 0].set_ylabel(r"$\Delta$ Power [dB]")
    axes[1, 0].set_xlabel("Time [s]")
    axes[1, 0].grid(True)
    add_state_vlines(axes[1, 0], nlos_to_los, los_to_nlos)

    axes[1, 1].plot(time, third_delay_difference, "k-", linewidth=1.2)
    axes[1, 1].set_ylabel(r"$\Delta$ Delay [$\mu$s]")
    axes[1, 1].set_xlabel("Time [s]")
    axes[1, 1].grid(True)
    add_state_vlines(axes[1, 1], nlos_to_los, los_to_nlos)

    axes[1, 2].plot(time, third_aoa_difference, "k-", linewidth=1.2)
    axes[1, 2].set_ylabel(r"$\Delta$ AoA [deg]")
    axes[1, 2].set_xlabel("Time [s]")
    axes[1, 2].grid(True)
    add_state_vlines(axes[1, 2], nlos_to_los, los_to_nlos)

    for column in range(3):
        axes[0, column].set_xlim(time.min(), time.max())

    figure.tight_layout()
    figure.savefig(
        output_filename,
        dpi=300,
        bbox_inches="tight",
    )
    plt.close(figure)


def plot_metric_grid(
    output_filename,
    time,
    values,
    differences,
    value_label,
    difference_label,
    nlos_to_los,
    los_to_nlos,
    minimum_value_span,
    minimum_difference,
):
    """Generate a 2x3 figure with each component and its per-sample change."""
    figure, axes = plt.subplots(2, 3, figsize=(16, 6), sharex="col")
    value_limits = padded_limits(values, minimum_span=minimum_value_span)
    difference_limits = symmetric_limits(differences, minimum=minimum_difference)

    for index, (label, value, difference) in enumerate(zip(COMPONENT_LABELS, values, differences)):
        axes[0, index].plot(time, value, color="black", linewidth=1.0)
        axes[0, index].set_title(label)
        axes[0, index].set_ylabel(value_label)
        axes[0, index].set_ylim(*value_limits)
        axes[0, index].grid(True)
        add_state_vlines(axes[0, index], nlos_to_los, los_to_nlos)

        axes[1, index].plot(time, difference, color="black", linewidth=1.0)
        axes[1, index].set_ylabel(difference_label)
        axes[1, index].set_xlabel("Time [s]")
        axes[1, index].set_ylim(*difference_limits)
        axes[1, index].grid(True)
        add_state_vlines(axes[1, index], nlos_to_los, los_to_nlos)

        axes[0, index].set_xlim(time.min(), time.max())

    figure.tight_layout()
    figure.savefig(output_filename, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_animation(
    output_filename,
    buildings,
    time,
    tx_x,
    tx_y,
    rx_x,
    rx_y,
    snr,
    snr_diff,
    nlos_to_los,
    los_to_nlos,
    x_limits,
    y_limits,
):
    """Generate the map and SNR animation."""
    figure, axes = plt.subplots(2, 2, figsize=(24, 9), dpi=150)
    map_axis, snr_axis = axes[0]
    zoom_axis, diff_axis = axes[1]

    add_buildings(map_axis, buildings)
    map_axis.set_xlabel("X [m]")
    map_axis.set_ylabel("Y [m]")
    map_axis.set_aspect("equal")
    map_axis.set_xlim(*x_limits)
    map_axis.set_ylim(*y_limits)
    tx_marker = map_axis.scatter([], [], marker="^", color="blue", s=80)
    rx_marker = map_axis.scatter([], [], marker="o", color="red", s=60)

    snr_axis.set_xlabel("Time [s]")
    snr_axis.set_ylabel("SNR [dB]")
    snr_axis.set_xlim(time.min(), time.max())
    snr_axis.set_ylim(*SNR_Y_LIMITS)
    snr_axis.grid(True)
    (snr_line,) = snr_axis.plot([], [], "k-", linewidth=1.5)
    add_state_vlines(snr_axis, nlos_to_los, los_to_nlos)
    add_state_legend(snr_axis, nlos_to_los, los_to_nlos)

    zoom_axis.set_xlabel("Time [s]")
    zoom_axis.set_ylabel("SNR [dB] (zoom)")
    zoom_axis.set_ylim(*SNR_Y_LIMITS)
    zoom_axis.grid(True)
    (zoom_line,) = zoom_axis.plot([], [], "k-", linewidth=1.5)
    add_state_vlines(zoom_axis, nlos_to_los, los_to_nlos)

    diff_axis.set_xlabel("Time [s]")
    diff_axis.set_ylabel(r"$\Delta$ SNR [dB]")
    diff_axis.set_xlim(time.min(), time.max())
    diff_axis.set_ylim(*SNR_DIFF_Y_LIMITS)
    diff_axis.grid(True)
    (diff_line,) = diff_axis.plot([], [], "k-", linewidth=1.5)
    add_state_vlines(diff_axis, nlos_to_los, los_to_nlos)

    maximum_frames = 800
    frame_step = max(1, len(time) // maximum_frames)
    frame_indices = list(range(0, len(time), frame_step))
    if frame_indices[-1] != len(time) - 1:
        frame_indices.append(len(time) - 1)

    def update(frame_index):
        timestamp = time.iloc[frame_index]
        tx_marker.set_offsets([[tx_x.iloc[frame_index], tx_y.iloc[frame_index]]])
        rx_marker.set_offsets([[rx_x.iloc[frame_index], rx_y.iloc[frame_index]]])
        map_axis.set_title(f"Time = {timestamp:.3f} s")

        snr_line.set_data(time.iloc[: frame_index + 1], snr.iloc[: frame_index + 1])
        start_time = max(time.min(), timestamp - ZOOM_WINDOW_S / 2.0)
        end_time = min(time.max(), timestamp + ZOOM_WINDOW_S / 2.0)
        mask = (time >= start_time) & (time <= end_time)
        zoom_axis.set_xlim(start_time, end_time)
        zoom_line.set_data(time[mask], snr[mask])
        diff_line.set_data(time.iloc[: frame_index + 1], snr_diff.iloc[: frame_index + 1])
        return tx_marker, rx_marker, snr_line, zoom_line, diff_line

    generated_animation = animation.FuncAnimation(
        figure,
        update,
        frames=frame_indices,
        interval=0,
        blit=False,
    )
    generated_animation.save(output_filename, writer="pillow", fps=25, dpi=90)
    plt.close(figure)


def plot_component_power_animation(
    output_filename,
    time,
    component_powers,
    component_power_differences,
    nlos_to_los,
    los_to_nlos,
):
    """Generate an animation of C1-C3 channel-component powers and their changes."""
    figure, axes = plt.subplots(2, 1, figsize=(12, 8), dpi=120, sharex=True)

    power_axis = axes[0]
    difference_axis = axes[1]

    power_axis.set_ylabel("Channel component power [dB]")
    power_axis.grid(True)
    power_axis.set_xlim(time.min(), time.max())
    power_axis.set_ylim(*padded_limits(component_powers, minimum_span=1.0))
    add_state_vlines(power_axis, nlos_to_los, los_to_nlos)

    difference_axis.set_xlabel("Time [s]")
    difference_axis.set_ylabel(r"$\Delta$ channel component power [dB]")
    difference_axis.grid(True)
    difference_axis.set_xlim(time.min(), time.max())
    difference_axis.set_ylim(*symmetric_limits(component_power_differences, minimum=0.1))
    add_state_vlines(difference_axis, nlos_to_los, los_to_nlos)

    power_lines = []
    difference_lines = []

    for index, (label, style, color) in enumerate(
        zip(COMPONENT_LABELS, COMPONENT_STYLES, COMPONENT_COLORS)
    ):
        (power_line,) = power_axis.plot(
            [],
            [],
            linestyle=style,
            color=color,
            linewidth=1.5,
            label=label,
            zorder=len(COMPONENT_LABELS) - index,
        )
        power_lines.append(power_line)

        (difference_line,) = difference_axis.plot(
            [],
            [],
            linestyle=style,
            color=color,
            linewidth=1.5,
            label=label,
            zorder=len(COMPONENT_LABELS) - index,
        )
        difference_lines.append(difference_line)

    power_axis.legend(loc="best")
    difference_axis.legend(loc="best")

    maximum_frames = 800
    frame_step = max(1, len(time) // maximum_frames)
    frame_indices = list(range(0, len(time), frame_step))

    if frame_indices[-1] != len(time) - 1:
        frame_indices.append(len(time) - 1)

    def update(frame_index):
        for index in range(3):
            power_lines[index].set_data(
                time.iloc[: frame_index + 1],
                component_powers[index].iloc[: frame_index + 1],
            )

            difference_lines[index].set_data(
                time.iloc[: frame_index + 1],
                component_power_differences[index].iloc[: frame_index + 1],
            )

        return (*power_lines, *difference_lines)

    generated_animation = animation.FuncAnimation(
        figure,
        update,
        frames=frame_indices,
        interval=0,
        blit=False,
    )

    generated_animation.save(
        output_filename,
        writer="pillow",
        fps=25,
        dpi=120,
    )

    plt.close(figure)


def main():
    options = parse_arguments()
    data = pd.read_csv(TRACE_FILE, sep=r"\s+", comment="#")
    buildings = pd.read_csv(BUILDINGS_FILE, sep=r"\s+", comment="#", header=None)

    required_columns = {
        TIME_COL,
        TX_X_COL,
        TX_Y_COL,
        RX_X_COL,
        RX_Y_COL,
        STATE_COL,
        SNR_COL,
        *CLUSTER_POWER_COLS,
        *COMPONENT_POWER_COLS,
        *DELAY_COLS,
        *AOA_COLS,
        *ZOA_COLS,
    }

    missing_columns = required_columns.difference(data.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise ValueError(f"Trace is missing required columns: {missing}")

    time = data[TIME_COL]
    tx_x = data[TX_X_COL]
    tx_y = data[TX_Y_COL]
    rx_x = data[RX_X_COL]
    rx_y = data[RX_Y_COL]
    state = data[STATE_COL].astype(str)
    snr = data[SNR_COL]
    snr_diff = snr.diff().fillna(0.0)

    cluster_powers = [data[column] for column in CLUSTER_POWER_COLS]
    component_powers = [data[column] for column in COMPONENT_POWER_COLS]
    delays_us = [data[column] * 1e6 for column in DELAY_COLS]
    aoas = [data[column] for column in AOA_COLS]
    zoas = [data[column] for column in ZOA_COLS]

    cluster_power_differences = [cluster.diff().fillna(0.0) for cluster in cluster_powers]
    component_power_differences = [component.diff().fillna(0.0) for component in component_powers]
    delay_differences_us = [component.diff().fillna(0.0) for component in delays_us]
    aoa_differences = [angular_difference_deg(component) for component in aoas]
    zoa_differences = [angular_difference_deg(component) for component in zoas]

    nlos_to_los, los_to_nlos = get_transition_times(time, state)
    x_limits, y_limits = scenario_limits(buildings, tx_x, tx_y, rx_x, rx_y)

    plot_scenario(
        "channel_consistency_scenario.png",
        buildings,
        tx_x,
        tx_y,
        rx_x,
        rx_y,
        x_limits,
        y_limits,
    )
    plot_snr(
        "channel_consistency_snr_and_dsnr.png",
        time,
        snr,
        snr_diff,
        nlos_to_los,
        los_to_nlos,
    )
    plot_cluster_overview(
        "channel_consistency_clusters.png",
        time,
        component_powers,
        delays_us,
        component_power_differences,
        delay_differences_us,
        nlos_to_los,
        los_to_nlos,
    )
    plot_metric_grid(
        "channel_consistency_cluster_power.png",
        time,
        cluster_powers,
        cluster_power_differences,
        "Cluster power [dB]",
        r"$\Delta$ cluster power [dB]",
        nlos_to_los,
        los_to_nlos,
        1.0,
        0.1,
    )
    plot_metric_grid(
        "channel_consistency_cluster_delay.png",
        time,
        delays_us,
        delay_differences_us,
        r"Delay [$\mu$s]",
        r"$\Delta$ delay [$\mu$s]",
        nlos_to_los,
        los_to_nlos,
        0.1,
        0.01,
    )
    plot_metric_grid(
        "channel_consistency_cluster_aoa.png",
        time,
        aoas,
        aoa_differences,
        "AoA [degrees]",
        r"$\Delta$ AoA [degrees]",
        nlos_to_los,
        los_to_nlos,
        1.0,
        0.1,
    )
    plot_metric_grid(
        "channel_consistency_cluster_zoa.png",
        time,
        zoas,
        zoa_differences,
        "ZoA [degrees]",
        r"$\Delta$ ZoA [degrees]",
        nlos_to_los,
        los_to_nlos,
        1.0,
        0.1,
    )

    plot_third_cluster_metrics(
        "third_cluster_varying_rates.png",
        time,
        cluster_powers,
        delays_us,
        aoas,
        cluster_power_differences,
        delay_differences_us,
        aoa_differences,
        nlos_to_los,
        los_to_nlos,
    )

    if options.animations:
        plot_animation(
            "3gpp-channel-consistency.gif",
            buildings,
            time,
            tx_x,
            tx_y,
            rx_x,
            rx_y,
            snr,
            snr_diff,
            nlos_to_los,
            los_to_nlos,
            x_limits,
            y_limits,
        )
        plot_component_power_animation(
            "channel_consistency_component_powers.gif",
            time,
            component_powers,
            component_power_differences,
            nlos_to_los,
            los_to_nlos,
        )


if __name__ == "__main__":
    main()
