/*
 * Copyright (c) 2024 DERONNE SOFTWARE ENGINEERING
 *
 * SPDX-License-Identifier: GPL-2.0-only
 *
 * Author: Sébastien Deronne <sebastien.deronne@gmail.com>
 */

#include "ns3/internet-stack-helper.h"
#include "ns3/ipv4-address-helper.h"
#include "ns3/ipv4-routing-helper.h"
#include "ns3/p2p-cache-helper.h"
#include "ns3/simple-channel.h"
#include "ns3/simple-net-device-helper.h"
#include "ns3/simple-net-device.h"
#include "ns3/simulator.h"
#include "ns3/test.h"

using namespace ns3;

/**
 * @ingroup internet-test
 *
 * @brief P2P Cache Test
 */
class P2pCacheTest : public TestCase
{
  public:
    P2pCacheTest();

  private:
    void DoRun() override;

    /**
     * @brief Verify ARP caches is populated as expected
     * @param expectedArpCaches The expected content of the ARP caches
     */
    void CheckArpCache(const std::string& expectedArpCaches);

    NodeContainer m_nodes; //!< Nodes used in the test.
};

P2pCacheTest::P2pCacheTest()
    : TestCase("The P2pCacheTest check if P2P caches are populated correctly.")
{
}

void
P2pCacheTest::CheckArpCache(const std::string& expectedArpCache)
{
    std::ostringstream stringStream;
    auto arpStream = Create<OutputStreamWrapper>(&stringStream);
    for (uint32_t i = 0; i < NodeList::GetNNodes(); ++i)
    {
        auto node = NodeList::GetNode(i);
        Ipv4RoutingHelper::PrintArpCache(node, arpStream, Time::S);
    }
    NS_TEST_EXPECT_MSG_EQ(stringStream.str(), expectedArpCache, "ARP cache is incorrect.");
}

void
P2pCacheTest::DoRun()
{
    m_nodes.Create(3);

    auto channel1 = CreateObject<SimpleChannel>();
    SimpleNetDeviceHelper simpleHelper1;
    auto netDevicesSubnet1 = simpleHelper1.Install(m_nodes.Get(0), channel1);
    netDevicesSubnet1.Add(simpleHelper1.Install(m_nodes.Get(1), channel1));

    auto channel2 = CreateObject<SimpleChannel>();
    SimpleNetDeviceHelper simpleHelper2;
    auto netDevicesSubnet2 = simpleHelper2.Install(m_nodes.Get(1), channel2);
    netDevicesSubnet2.Add(simpleHelper2.Install(m_nodes.Get(2), channel2));

    InternetStackHelper internet;
    internet.Install(m_nodes);

    // Setup IPv4 addresses
    Ipv4AddressHelper ipv4;
    ipv4.SetBase("10.1.1.0", "255.255.255.0");
    auto ipv4Interfaces1 = ipv4.Assign(netDevicesSubnet1);
    ipv4.SetBase("10.1.2.0", "255.255.255.0");
    auto ipv4Interfaces2 = ipv4.Assign(netDevicesSubnet2);

    std::cerr << "ipv4Interfaces2=" << ipv4Interfaces2.GetAddress(1) << std::endl;

    // Populate ARP cache for node 1
    P2pCacheHelper p2pCache;
    p2pCache.PopulateP2pCache(netDevicesSubnet1.Get(1), netDevicesSubnet1.Get(0));
    p2pCache.PopulateP2pCache(netDevicesSubnet2.Get(0), netDevicesSubnet2.Get(1));

    // Check if ARP cache is populated correctly for node 1, ARP caches of other nodes should be
    // empty
    std::ostringstream expectedArpCaches;
    expectedArpCaches << "ARP Cache of node 0 at time 0\n"
                      << "ARP Cache of node 1 at time 0\n"
                      << ipv4Interfaces1.GetAddress(0) << " dev 0 lladdr "
                      << netDevicesSubnet1.Get(0)->GetAddress() << " STATIC_AUTOGENERATED\n"
                      << ipv4Interfaces2.GetAddress(1) << " dev 1 lladdr "
                      << netDevicesSubnet2.Get(1)->GetAddress() << " STATIC_AUTOGENERATED\n"
                      << "ARP Cache of node 2 at time 0\n";
    Simulator::ScheduleNow(&P2pCacheTest::CheckArpCache, this, expectedArpCaches.str());

    Simulator::Run();
    Simulator::Destroy();
}

/**
 * @ingroup internet-test
 *
 * @brief P2P Cache TestSuite
 */
class P2pCacheTestSuite : public TestSuite
{
  public:
    P2pCacheTestSuite()
        : TestSuite("p2p-cache", Type::UNIT)
    {
        AddTestCase(new P2pCacheTest, TestCase::Duration::QUICK);
    }
};

static P2pCacheTestSuite g_p2pCacheTestSuite; //!< Static variable for test initialization
