/*
 * SPDX-License-Identifier: GPL-2.0-only
 */

#include "tcp-error-model.h"
#include "tcp-general-test.h"

#include "ns3/config.h"
#include "ns3/log.h"
#include "ns3/node.h"
#include "ns3/simulator.h"
#include "ns3/tcp-tx-buffer.h"

using namespace ns3;

NS_LOG_COMPONENT_DEFINE("TcpNoSackDupAckTestSuite");

/**
 * @ingroup internet-test
 *
 * @brief A socket that can send an additional (duplicate) ACK on request.
 */
class TcpSocketDupAcker : public TcpSocketMsgBase
{
  public:
    /**
     * @brief Get the type ID.
     * @return the object TypeId
     */
    static TypeId GetTypeId();

    TcpSocketDupAcker()
        : TcpSocketMsgBase()
    {
    }

    /**
     * @brief Constructor.
     * @param other The object to copy from.
     */
    TcpSocketDupAcker(const TcpSocketDupAcker& other)
        : TcpSocketMsgBase(other)
    {
    }

    /**
     * @brief Send a pure ACK that repeats the current acknowledgment number.
     */
    void SendDupAck();

  protected:
    Ptr<TcpSocketBase> Fork() override;
};

NS_OBJECT_ENSURE_REGISTERED(TcpSocketDupAcker);

TypeId
TcpSocketDupAcker::GetTypeId()
{
    static TypeId tid = TypeId("ns3::TcpSocketDupAcker")
                            .SetParent<TcpSocketMsgBase>()
                            .SetGroupName("Internet")
                            .AddConstructor<TcpSocketDupAcker>();
    return tid;
}

void
TcpSocketDupAcker::SendDupAck()
{
    SendEmptyPacket(TcpHeader::ACK);
}

Ptr<TcpSocketBase>
TcpSocketDupAcker::Fork()
{
    return CopyObject<TcpSocketDupAcker>(this);
}

/**
 * @ingroup internet-test
 *
 * @brief Check that, without SACK, duplicate ACKs below the threshold do not
 * cause a loss to be inferred (see @issueid{1107}).
 *
 * Without SACK, the sender accounts for each duplicate ACK by guessing that
 * a segment has been SACKed. The receiver of this test sends some additional
 * duplicate ACKs, so that the sender holds more guesses than the segments
 * actually received out of order. The test checks that those guesses are
 * dropped when the cumulative ACK advances outside of fast recovery, or
 * ends it, instead of being turned into a lost segment.
 *
 * Two scenarios are supported. With no segment dropped, the receiver
 * duplicates two consecutive ACKs, each of which acknowledges one segment:
 * the sender must never enter fast recovery nor retransmit. With one segment
 * dropped, the receiver sends one additional duplicate ACK during fast
 * recovery: the sender must enter fast recovery once and retransmit only
 * the dropped segment.
 */
class TcpNoSackDupAckTest : public TcpGeneralTest
{
  public:
    /**
     * @brief Constructor.
     * @param desc Description.
     * @param toDrop Sequence number of the segment to drop (0 to drop none).
     */
    TcpNoSackDupAckTest(const std::string& desc, uint32_t toDrop);

  protected:
    void ConfigureEnvironment() override;
    void ConfigureProperties() override;
    Ptr<TcpSocketMsgBase> CreateReceiverSocket(Ptr<Node> node) override;
    Ptr<ErrorModel> CreateReceiverErrorModel() override;
    void Tx(const Ptr<const Packet> p, const TcpHeader& h, SocketWho who) override;
    void CongStateTrace(const TcpSocketState::TcpCongState_t oldValue,
                        const TcpSocketState::TcpCongState_t newValue) override;
    void FinalChecks() override;

  private:
    /**
     * @brief Make the receiver send an additional duplicate ACK.
     */
    void InjectDupAck();

    uint32_t m_toDrop;               //!< Sequence number to drop (0 to drop none)
    SequenceNumber32 m_highestSeqTx; //!< Highest sequence number sent by the sender
    SequenceNumber32 m_lastAckTx;    //!< Last ACK number sent by the receiver
    uint32_t m_advancingAcks{0};     //!< ACKs sent by the receiver that advance the ACK number
    uint32_t m_receiverDupAcks{0};   //!< Duplicate ACKs generated by the receiver itself
    uint32_t m_injectedDupAcks{0};   //!< Additional duplicate ACKs injected by the test
    bool m_injecting{false};         //!< True while an additional duplicate ACK is being sent
    uint32_t m_retransmissions{0};   //!< Data segments retransmitted by the sender
    uint32_t m_disorderEntries{0};   //!< Number of times the sender entered CA_DISORDER
    uint32_t m_recoveryEntries{0};   //!< Number of times the sender entered CA_RECOVERY
    uint32_t m_lossEntries{0};       //!< Number of times the sender entered CA_LOSS
};

TcpNoSackDupAckTest::TcpNoSackDupAckTest(const std::string& desc, uint32_t toDrop)
    : TcpGeneralTest(desc),
      m_toDrop(toDrop),
      m_highestSeqTx(0),
      m_lastAckTx(1)
{
}

void
TcpNoSackDupAckTest::ConfigureEnvironment()
{
    TcpGeneralTest::ConfigureEnvironment();
    SetAppPktCount(60);
    SetPropagationDelay(MilliSeconds(50));
    SetTransmitStart(Seconds(2));

    Config::SetDefault("ns3::TcpSocketBase::Sack", BooleanValue(false));
}

void
TcpNoSackDupAckTest::ConfigureProperties()
{
    TcpGeneralTest::ConfigureProperties();
    SetInitialCwnd(SENDER, 10);
    // Every data segment is acknowledged by its own ACK
    SetDelAckMaxCount(RECEIVER, 1);
}

Ptr<TcpSocketMsgBase>
TcpNoSackDupAckTest::CreateReceiverSocket(Ptr<Node> node)
{
    return CreateSocket(node, TcpSocketDupAcker::GetTypeId(), m_congControlTypeId);
}

Ptr<ErrorModel>
TcpNoSackDupAckTest::CreateReceiverErrorModel()
{
    Ptr<TcpSeqErrorModel> errorModel = CreateObject<TcpSeqErrorModel>();
    if (m_toDrop != 0)
    {
        errorModel->AddSeqToKill(SequenceNumber32(m_toDrop));
    }
    return errorModel;
}

void
TcpNoSackDupAckTest::InjectDupAck()
{
    Ptr<TcpSocketDupAcker> receiver = DynamicCast<TcpSocketDupAcker>(GetReceiverSocket());
    NS_TEST_ASSERT_MSG_NE(receiver, nullptr, "The receiver is not a TcpSocketDupAcker");

    m_injecting = true;
    receiver->SendDupAck();
    m_injecting = false;
}

void
TcpNoSackDupAckTest::Tx(const Ptr<const Packet> p, const TcpHeader& h, SocketWho who)
{
    if (who == SENDER)
    {
        if (p->GetSize() == 0)
        {
            return;
        }

        if (h.GetSequenceNumber() <= m_highestSeqTx)
        {
            NS_LOG_DEBUG("Retransmission of seq=" << h.GetSequenceNumber());
            ++m_retransmissions;
            if (m_toDrop != 0)
            {
                NS_TEST_ASSERT_MSG_EQ(h.GetSequenceNumber(),
                                      SequenceNumber32(m_toDrop),
                                      "Retransmitted a segment that was not dropped");
            }
        }
        else
        {
            m_highestSeqTx = h.GetSequenceNumber();
        }
        return;
    }

    if (p->GetSize() != 0 || h.GetFlags() != TcpHeader::ACK)
    {
        return;
    }

    if (m_injecting)
    {
        NS_LOG_DEBUG("Additional dupack sent, ack=" << h.GetAckNumber());
        ++m_injectedDupAcks;
        return;
    }

    bool inject = false;
    if (h.GetAckNumber() > m_lastAckTx)
    {
        m_lastAckTx = h.GetAckNumber();
        ++m_advancingAcks;
        // With no drop, duplicate two consecutive ACKs
        inject = (m_toDrop == 0 && (m_advancingAcks == 3 || m_advancingAcks == 4));
    }
    else
    {
        ++m_receiverDupAcks;
        // With a drop, add a dupack once the sender is in fast recovery
        inject = (m_toDrop != 0 && m_receiverDupAcks == 5);
    }

    if (inject)
    {
        // The ACK that is being traced has to leave the socket first
        Simulator::ScheduleNow(&TcpNoSackDupAckTest::InjectDupAck, this);
    }
}

void
TcpNoSackDupAckTest::CongStateTrace(const TcpSocketState::TcpCongState_t oldValue,
                                    const TcpSocketState::TcpCongState_t newValue)
{
    NS_LOG_DEBUG(TcpSocketState::TcpCongStateName[oldValue]
                 << " -> " << TcpSocketState::TcpCongStateName[newValue]);

    switch (newValue)
    {
    case TcpSocketState::CA_DISORDER:
        ++m_disorderEntries;
        break;
    case TcpSocketState::CA_RECOVERY:
        ++m_recoveryEntries;
        break;
    case TcpSocketState::CA_LOSS:
        ++m_lossEntries;
        break;
    case TcpSocketState::CA_OPEN:
        NS_TEST_ASSERT_MSG_EQ(GetTxBuffer(SENDER)->GetLost(),
                              0,
                              "A segment is marked as lost when going back to CA_OPEN from "
                                  << TcpSocketState::TcpCongStateName[oldValue]);
        NS_TEST_ASSERT_MSG_EQ(GetTxBuffer(SENDER)->GetSacked(),
                              0,
                              "A guessed SACK is left when going back to CA_OPEN from "
                                  << TcpSocketState::TcpCongStateName[oldValue]);
        break;
    default:
        break;
    }
}

void
TcpNoSackDupAckTest::FinalChecks()
{
    NS_TEST_ASSERT_MSG_EQ(m_lossEntries, 0, "The sender experienced a retransmission timeout");

    if (m_toDrop == 0)
    {
        NS_TEST_ASSERT_MSG_EQ(m_injectedDupAcks, 2, "Additional dupacks not sent");
        NS_TEST_ASSERT_MSG_EQ(m_disorderEntries, 2, "The dupacks did not reach the sender");
        NS_TEST_ASSERT_MSG_EQ(m_recoveryEntries, 0, "Fast recovery entered without a loss");
        NS_TEST_ASSERT_MSG_EQ(m_retransmissions, 0, "Segment retransmitted without a loss");
    }
    else
    {
        NS_TEST_ASSERT_MSG_EQ(m_injectedDupAcks, 1, "Additional dupack not sent");
        NS_TEST_ASSERT_MSG_EQ(m_recoveryEntries, 1, "Fast recovery not entered exactly once");
        NS_TEST_ASSERT_MSG_EQ(m_retransmissions, 1, "Not exactly one segment retransmitted");
    }
}

/**
 * @ingroup internet-test
 *
 * @brief TestSuite: duplicate ACK handling when SACK is disabled
 */
class TcpNoSackDupAckTestSuite : public TestSuite
{
  public:
    TcpNoSackDupAckTestSuite()
        : TestSuite("tcp-no-sack-dupack-test", Type::UNIT)
    {
        AddTestCase(new TcpNoSackDupAckTest("Additional dupack in fast recovery, one drop", 1001),
                    TestCase::Duration::QUICK);
        AddTestCase(new TcpNoSackDupAckTest("Dupacks below the threshold, no drop", 0),
                    TestCase::Duration::QUICK);
    }
};

static TcpNoSackDupAckTestSuite
    g_tcpNoSackDupAckTestSuite; //!< Static variable for test initialization
