/*
 * Copyright (c) 2025 Universita' degli Studi di Napoli Federico II
 *
 * SPDX-License-Identifier: GPL-2.0-only
 *
 * Author: Stefano Avallone <stavallo@unina.it>
 */
#ifndef COEX_EVENT_H
#define COEX_EVENT_H

#include "ns3/nstime.h"

#include <type_traits>
#include <utility>
#include <variant>

namespace ns3
{
namespace coex
{

/**
 * @ingroup coex
 *
 * Enumeration of the Radio Access Technologies (RAT) using the coex framework
 */
enum class Rat : uint8_t
{
    UNDEFINED = 0,
    WIFI,
};

/**
 * @ingroup coex
 *
 * Enumeration of the types of Coex events generated by a Wi-Fi device
 */
enum class WifiCoexEventType : uint8_t
{
    UNDEFINED = 0,
    START_TX,
    START_TX_CTL,
    START_TX_MGT,
    START_RX,
    START_RX_CTL,
    START_RX_MGT,
    START_RX_BEACON,
    START_RTS,
    STOP_TX,
    STOP_RX,
    TX_ABORTED,
};

/**
 * @ingroup coex
 *
 * Coex event type.
 */
class EventType
{
    friend std::ostream& operator<<(std::ostream&, const EventType&);

  public:
    constexpr EventType() = default;

    /**
     * Construct a coex event type based on a coex event type for a certain RAT.
     *
     * @tparam T @deduced the type of a RAT coex event type
     * @param evType a RAT coex event type
     */
    template <class T>
    constexpr EventType(T evType)
        : m_eventType(evType)
    {
    }

    /// @return the RAT corresponding to this coex event type.
    constexpr Rat GetRat() const
    {
        return static_cast<Rat>(m_eventType.index());
    }

    /**
     * Get this coex event type as a coex event type of the corresponding RAT.
     *
     * Note that the explicit template type parameter must match the type returned by GetRat().
     *
     * @tparam T @explicit the type of a RAT coex event type
     * @return the coex event type of the corresponding RAT
     */
    template <class T>
    constexpr T GetType() const
    {
        return std::get<T>(m_eventType);
    }

  private:
    /// Coex event type variant (types must be listed in the same order as Rat enum)
    using Type = std::variant<std::monostate, WifiCoexEventType>;

    Type m_eventType; ///< coex event type
};

/**
 * @ingroup coex
 * @brief Coex Event
 *
 * A coex event that is notified to/by the Coex Arbitrator.
 */
struct Event
{
    EventType type;   ///< the coex event type
    Time start;       ///< absolute start time of the coex event
    Time duration;    ///< duration of the coex event
    Time periodicity; ///< the periodicity of the coex event, if non-zero
};

/**
 * @brief Stream insertion operator.
 *
 * @param os the stream
 * @param rat the Radio Access Technology
 * @returns a reference to the stream
 */
inline std::ostream&
operator<<(std::ostream& os, Rat rat)
{
    switch (rat)
    {
    case Rat::UNDEFINED:
        return (os << "UNDEFINED");
    case Rat::WIFI:
        return (os << "WIFI");
    default:
        NS_ABORT_MSG("Unexpected value " << static_cast<uint16_t>(rat));
        return os;
    }
}

/**
 * @brief Stream insertion operator.
 *
 * @param os the stream
 * @param evType the Wi-Fi coex event type
 * @returns a reference to the stream
 */
inline std::ostream&
operator<<(std::ostream& os, WifiCoexEventType evType)
{
    using enum WifiCoexEventType;
    switch (evType)
    {
    case UNDEFINED:
        return (os << "UNDEFINED");
    case START_TX:
        return (os << "START_TX");
    case START_TX_CTL:
        return (os << "START_TX_CTL");
    case START_TX_MGT:
        return (os << "START_TX_MGT");
    case START_RX:
        return (os << "START_RX");
    case START_RX_CTL:
        return (os << "START_RX_CTL");
    case START_RX_MGT:
        return (os << "START_RX_MGT");
    case START_RX_BEACON:
        return (os << "START_RX_BEACON");
    case START_RTS:
        return (os << "START_RTS");
    case STOP_TX:
        return (os << "STOP_TX");
    case STOP_RX:
        return (os << "STOP_RX");
    case TX_ABORTED:
        return (os << "TX_ABORTED");
    default:
        NS_ABORT_MSG("Unexpected value " << static_cast<uint16_t>(evType));
        return os;
    }
}

/**
 * @brief Stream insertion operator.
 *
 * @param os the stream
 * @param evType the coex event type
 * @returns a reference to the stream
 */
inline std::ostream&
operator<<(std::ostream& os, const EventType& evType)
{
    os << evType.GetRat();

    return std::visit(
        [&](const auto ev) -> std::ostream& {
            using T = std::decay_t<decltype(ev)>;
            if constexpr (!std::is_same_v<T, std::monostate>)
            {
                return (os << "_" << ev);
            }
            return os;
        },
        evType.m_eventType);
}

/**
 * @brief Stream insertion operator.
 *
 * @param os the stream
 * @param event the coex event
 * @returns a reference to the stream
 */
inline std::ostream&
operator<<(std::ostream& os, const Event& event)
{
    return (os << event.type << "[start: " << event.start.As(Time::S)
               << ", duration:" << event.duration.As(Time::US)
               << ", periodicity: " << event.periodicity.As(Time::US) << "]");
}

} // namespace coex
} // namespace ns3

#endif /* COEX_EVENT_H */
