## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('flow-monitor', ['internet', 'config-store', 'stats'])
    obj.source = ["model/%s" % s for s in [
       'flow-monitor.cc',
       'flow-classifier.cc',
       'flow-probe.cc',
       'ipv4-flow-classifier.cc',
       'ipv4-flow-probe.cc',
       'ipv6-flow-classifier.cc',
       'ipv6-flow-probe.cc',
        ]]
    obj.source.append("helper/flow-monitor-helper.cc")

    module_test = bld.create_ns3_module_test_library('flow-monitor')
    module_test.source = [ ]

    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #   'test/flow-monitor-examples-test-suite.cc',
            ])
    
    headers = bld(features='ns3header')
    headers.module = 'flow-monitor'
    headers.source = ["model/%s" % s for s in [
       'flow-monitor.h',
       'flow-probe.h',
       'flow-classifier.h',
       'ipv4-flow-classifier.h',
       'ipv4-flow-probe.h',
       'ipv6-flow-classifier.h',
       'ipv6-flow-probe.h',
        ]]
    headers.source.append("helper/flow-monitor-helper.h")

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
