/*
 * Copyright (c) 2024 DERONNE SOFTWARE ENGINEERING
 *
 * SPDX-License-Identifier: GPL-2.0-only
 *
 * Author: Sébastien Deronne <sebastien.deronne@gmail.com>
 */

#include "p2p-cache-helper.h"

#include "ns3/arp-cache.h"
#include "ns3/ipv4-address.h"
#include "ns3/ipv4-interface.h"
#include "ns3/ipv4-l3-protocol.h"
#include "ns3/ipv4.h"
#include "ns3/log.h"
#include "ns3/net-device.h"
#include "ns3/node.h"

namespace ns3
{

NS_LOG_COMPONENT_DEFINE("P2pCacheHelper");

P2pCacheHelper::P2pCacheHelper()
{
    NS_LOG_FUNCTION(this);
}

P2pCacheHelper::~P2pCacheHelper()
{
    NS_LOG_FUNCTION(this);
}

void
P2pCacheHelper::PopulateP2pCache(Ptr<NetDevice> netDevice, Ptr<NetDevice> peerDevice) const
{
    NS_LOG_FUNCTION(this);

    if (peerDevice == netDevice)
    {
        return;
    }

    auto node = netDevice->GetNode();
    const auto ipv4InterfaceIndex = node->GetObject<Ipv4>()->GetInterfaceForDevice(netDevice);
    if (ipv4InterfaceIndex == -1)
    {
        return;
    }

    auto peerNode = peerDevice->GetNode();
    auto peerIpv4InterfaceIndex = peerNode->GetObject<Ipv4>()->GetInterfaceForDevice(peerDevice);
    if (peerIpv4InterfaceIndex == -1)
    {
        return;
    }

    auto ipv4Interface = node->GetObject<Ipv4L3Protocol>()->GetInterface(ipv4InterfaceIndex);
    auto peerIpv4Interface =
        peerNode->GetObject<Ipv4L3Protocol>()->GetInterface(peerIpv4InterfaceIndex);
    PopulateP2pEntries(ipv4Interface, peerIpv4Interface);
}

void
P2pCacheHelper::PopulateP2pEntries(Ptr<Ipv4Interface> ipv4Interface,
                                   Ptr<Ipv4Interface> peerDeviceInterface) const
{
    auto netDeviceAddresses = ipv4Interface->GetNAddresses();
    auto peerDeviceAddresses = peerDeviceInterface->GetNAddresses();
    for (uint32_t devAddrIndex = 0; devAddrIndex < netDeviceAddresses; ++devAddrIndex)
    {
        auto netDeviceIfAddr = ipv4Interface->GetAddress(devAddrIndex);
        for (uint32_t addressIndex = 0; addressIndex < peerDeviceAddresses; ++addressIndex)
        {
            auto peerDeviceIfAddr = peerDeviceInterface->GetAddress(addressIndex);
            if (netDeviceIfAddr.IsInSameSubnet(peerDeviceIfAddr.GetLocal()))
            {
                auto peerDevice = peerDeviceInterface->GetDevice();
                // Add ARP entry of peer interface to current interface's ARP cache
                AddEntry(ipv4Interface,
                         peerDeviceIfAddr.GetAddress(),
                         peerDevice->GetAddressFor(ipv4Interface->GetDevice()->GetAddress()));
            }
        }
    }
}

void
P2pCacheHelper::AddEntry(Ptr<Ipv4Interface> netDeviceInterface,
                         const Ipv4Address& ipv4Address,
                         const Address& macAddress) const
{
    NS_LOG_FUNCTION(this << netDeviceInterface << ipv4Address << macAddress);
    auto arpCache = netDeviceInterface->GetArpCache();
    if (!arpCache)
    {
        NS_LOG_LOGIC(
            "ArpCache doesn't exist, might be a point-to-point NetDevice without ArpCache");
        return;
    }
    auto entry = arpCache->Lookup(ipv4Address);
    if (!entry)
    {
        NS_LOG_LOGIC("ADD an ARP entry to cache " << arpCache << ": " << ipv4Address << " is at "
                                                  << macAddress);
        entry = arpCache->Add(ipv4Address);
    }
    entry->SetMacAddress(macAddress);
    entry->MarkAutoGenerated();
}

} // namespace ns3
